#!/usr/bin/env python
"""
 * ss7mon_cmd
 *
 * SS7 message monitor command helper for Sangoma devices
 *
 * Moises Silva <moises.silva@gmail.com>
 * Copyright (C) System One NOC
 * Copyright (C) N-SOFT
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contributors:
 *
"""

from __future__ import print_function
import sys
import zmq
import time
import re
from optparse import OptionParser


def execute_command(context, server_addr, command):
    """ Execute a command in the provided server addr """
    socket = None
    try:
        socket = context.socket(zmq.REQ)
        if socket is None:
            print("Failed to create zmq socket to connect at address {}"
                  .format(server_addr))
            return False
        socket.connect(server_addr)
        socket.send(command, 0, True, False)
        read_cnt = 0
        response = None
        while read_cnt < 50:
            read_cnt += 1
            time.sleep(0.1)
            try:
                response = socket.recv(flags=zmq.NOBLOCK)
                if response is not None:
                    break
            except zmq.error.Again:
                pass
        if response is None:
            print("Timed out waiting for response from server {}"
                  .format(server_addr))
        else:
            print(response)

    except KeyboardInterrupt:
        print("Quitting ...")
        return False
    except:
        exc_type, exc_value, exc_traceback = sys.exc_info()
        print("Could not execute command on server {}: {}/{}"
              .format(server_addr, exc_type, exc_value))
    if socket:
        socket.close()


def run():
    """ Run the command execution client """
    parser = OptionParser()
    parser.add_option("-d", "--dev", dest="device",
                      help="Specify device in sXcY format",
                      metavar="DEVICE")

    parser.add_option("-s", "--span", dest="span",
                      help=("Specify span (not used if -d or "
                            "--dev is specified)"),
                      metavar="SPAN")

    parser.add_option("-c", "--channels", dest="chans",
                      help=("Specify channel or range of channels, "
                            "ie 1 or 1,30 (not used if -d or --dev is "
                            "specified)"),
                      metavar="CHANNELS")

    parser.add_option("-e", "--execute", dest="command",
                      help="Specify command to execute",
                      metavar="COMMAND")

    parser.add_option("-a", "--address", dest="server_addr",
                      help=("Optional server address "
                            "(ie tcp://127.0.0.1:5555/ "
                            "or ipc:///tmp/s1c1 etc)"),
                      metavar="SERVER_ADDRESS")

    (options, args) = parser.parse_args()

    span = 0
    start_chan = 0
    end_chan = 0
    server_addr = ''
    context = zmq.Context()

    if options.command is None:
        parser.print_help()
        parser.error("-e or --execute is required to specify "
                     "the command to execute")

    if options.server_addr:
        server_addr = options.server_addr
        if options.device or options.span or options.chans:
            parser.print_help()
            parser.error("-a or --address cannot be used with -s "
                         "and -c or -d")
    elif options.device is None:
        if options.span is None or options.chans is None:
            parser.print_help()
            parser.error("Either both -s and -c or -d are required to specify "
                         "which device(s) to execute the command on when "
                         "no address is specified with -a")
        span = int(options.span)
        options.chans = str(options.chans)
        i = options.chans.find(',')
        if i == -1:
            start_chan = int(options.chans)
            end_chan = start_chan + 1
        else:
            start_chan = int(options.chans[:i])
            end_chan = int(options.chans[i+1:]) + 1
    else:
        devspec = re.search(r's(\d+)c(\d+)', options.device)
        if devspec is None:
            parser.print_help()
            parser.error("Invalid string format '{}' for device"
                         .format(options.device))
        span = int(devspec.group(1))
        start_chan = int(devspec.group(2))
        end_chan = start_chan + 1

    if start_chan:
        for chan in range(start_chan, end_chan):
            server_addr = "ipc:////tmp/sng_ss7mon-s%dc%d" % (span, chan)
            execute_command(context, server_addr, options.command)
    else:
        execute_command(context, server_addr, options.command)

    sys.exit(0)


if __name__ == '__main__':
    run()
